In [1]:
# simplest data to work with : tiny shakespare 
with open('input.txt', 'r') as f:
    text = f.read()
data = text[:1000]
print(data[:100])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You


In [4]:
import tiktoken
enc = tiktoken.get_encoding('gpt2')
tokens = enc.encode(data)
print(tokens)

[5962, 22307, 25, 198, 8421, 356, 5120, 597, 2252, 11, 3285, 502, 2740, 13, 198, 198, 3237, 25, 198, 5248, 461, 11, 2740, 13, 198, 198, 5962, 22307, 25, 198, 1639, 389, 477, 12939, 2138, 284, 4656, 621, 284, 1145, 680, 30, 198, 198, 3237, 25, 198, 4965, 5634, 13, 12939, 13, 198, 198, 5962, 22307, 25, 198, 5962, 11, 345, 760, 327, 1872, 385, 1526, 28599, 318, 4039, 4472, 284, 262, 661, 13, 198, 198, 3237, 25, 198, 1135, 760, 470, 11, 356, 760, 470, 13, 198, 198, 5962, 22307, 25, 198, 5756, 514, 1494, 683, 11, 290, 356, 1183, 423, 11676, 379, 674, 898, 2756, 13, 198, 3792, 470, 257, 15593, 30, 198, 198, 3237, 25, 198, 2949, 517, 3375, 319, 470, 26, 1309, 340, 307, 1760, 25, 1497, 11, 1497, 0, 198, 198, 12211, 22307, 25, 198, 3198, 1573, 11, 922, 4290, 13, 198, 198, 5962, 22307, 25, 198, 1135, 389, 17830, 3595, 4290, 11, 262, 1458, 1173, 1547, 922, 13, 198, 2061, 4934, 969, 5036, 896, 319, 561, 26958, 514, 25, 611, 484, 198, 19188, 7800, 514, 475, 262, 48713, 414, 11, 981, 340, 547, 198, 

In [5]:
# now we want to take these tokens and forward them in our GPT model 
# to do that we have reshape our long list of token sequence into a (B, T) tensor 
# before that tha shape our forward function takes
# take an example of 24 tokens to understand this

import torch
buf = torch.tensor(tokens[:24])
x = buf.view(4, 6)
x 

tensor([[ 5962, 22307,    25,   198,  8421,   356],
        [ 5120,   597,  2252,    11,  3285,   502],
        [ 2740,    13,   198,   198,  3237,    25],
        [  198,  5248,   461,    11,  2740,    13]])

- So, that's our input to the transformer. Now, we also need labels to calucate the loss function. 
- For this we can write some code in the forward pass of the GPT model, as we know the next sequence is just the right of us. But the problem with that approch is that the for the token 13 (the last toke) we don't have the label information. 
- So Andrej fav way to do this, is that we will create the another tensor label of exact same size as x but it contains the labels at every position. 


In [7]:
# so, in the buf we get the last token + 1 and then index our x and y 
buf = torch.tensor(tokens[:24 + 1 ])
x = buf[:-1].view(4, 6) 
y = buf[1:].view(4, 6) 
x, y 

(tensor([[ 5962, 22307,    25,   198,  8421,   356],
         [ 5120,   597,  2252,    11,  3285,   502],
         [ 2740,    13,   198,   198,  3237,    25],
         [  198,  5248,   461,    11,  2740,    13]]),
 tensor([[22307,    25,   198,  8421,   356,  5120],
         [  597,  2252,    11,  3285,   502,  2740],
         [   13,   198,   198,  3237,    25,   198],
         [ 5248,   461,    11,  2740,    13,   198]]))

- Now we go back to our script and create a very simpel dataloader object to load these tokens, feed them to transformer and calculate the loss. 

----- 

Now, we want to calculate the loss function and to do so we have to modify the forward pass

using device: cuda
Only loading first 1k charchters as model input
logits shape torch.Size([4, 32, 50257])
loss tensor(11.0371, device='cuda:0', grad_fn=<NllLossBackward0>)

In [14]:
import math
1/ 50257, -math.log(50257)

(1.9897725689953638e-05, -10.82490511970208)

In [ ]:
optimizer = torch.optim.AdamW(model.parameters(), lr=3e-4)
for i in range(50):
    optimizer.zero_grad()
    logits, loss = model(x, y)
    loss.backward()
    optimizer.step()
    print(f"step {i}, loss: {loss.item()}")

# when we use this we are overfitting on the one batch x that we are passing again and again.
# lr = 3e-4 : is like good standard learning rate for early debugging stage. 


- Next, we don't want to overfit our model on that one batch. We want to create the a data loader which makes sure that we are getting a fresh batch. |

- num of batches in a single epoch of iterating over a single dataset
- So 1 epoch : how many unique batches do we output/iterate over before we loop back begining of the document and start reading it again. 
1000/ (4 * 32)

In [18]:
1000 // (4 * 32), 1115394 // (4 * 32) # 1115394: num of charachter but we have to use the num 
# of tokens
# So 

(7, 8714)

In [ ]:
# 1 epoch => num of tokens // (B, T)

In [20]:
# tiktokener have roughly about 1 to 3 compression ratio

In [19]:
# using device: cuda
# loaded 338025 tokens
# 1 epoch = 2640 batches
# step 0, loss: 11.08803939819336
# step 1, loss: 9.717626571655273
# step 2, loss: 8.71585750579834
# step 3, loss: 8.921952247619629
# step 4, loss: 8.44729995727539
# step 5, loss: 8.131488800048828
# step 6, loss: 9.005425453186035
# step 7, loss: 8.671504020690918
# step 8, loss: 8.075515747070312
# step 9, loss: 7.828042984008789
# step 10, loss: 8.26616096496582
# step 11, loss: 7.185250282287598
# step 12, loss: 7.63140869140625
# step 13, loss: 7.262790679931641
# step 14, loss: 7.483865261077881
# step 15, loss: 7.127208232879639
# step 16, loss: 7.217015743255615
# step 17, loss: 8.252432823181152
# step 18, loss: 7.073562145233154
# step 19, loss: 7.671370029449463
# step 20, loss: 7.384253025054932
# step 21, loss: 7.580746173858643
# step 22, loss: 6.214944839477539
# step 23, loss: 6.54738712310791
# step 24, loss: 6.535855293273926
# step 25, loss: 6.208362579345703
# step 26, loss: 6.298552989959717
# step 27, loss: 7.4446821212768555
# step 28, loss: 6.870301723480225
# step 29, loss: 6.647202968597412
# step 30, loss: 6.902033805847168
# step 31, loss: 6.967312335968018
# step 32, loss: 6.967711448669434
# step 33, loss: 6.67465353012085
# step 34, loss: 7.907723426818848
# step 35, loss: 7.669620513916016
# step 36, loss: 7.351398944854736
# step 37, loss: 7.470437049865723
# step 38, loss: 7.569716453552246
# step 39, loss: 7.141706943511963
# step 40, loss: 7.261336803436279
# step 41, loss: 6.442892551422119
# step 42, loss: 6.642857551574707
# step 43, loss: 6.760526180267334
# step 44, loss: 6.7352776527404785
# step 45, loss: 6.635310173034668
# step 46, loss: 5.62755012512207
# step 47, loss: 5.949457168579102
# step 48, loss: 6.788867473602295
# step 49, loss: 6.460808753967285

## Bug while loading the weight from hugging face 

In [22]:
from transformers import GPT2LMHeadModel
model_hf = GPT2LMHeadModel.from_pretrained('gpt2') 
sd_hf = model_hf.state_dict()


/home/shubham/projects/pytorch-concepts/torchenv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [25]:
print(sd_hf['lm_head.weight'].shape)
print(sd_hf["transformer.wte.weight"].shape)

torch.Size([50257, 768])
torch.Size([50257, 768])


In [ ]:
# transformer.wte : is the token embedding at the bottom of the transformer
# lm_head : is the language modeling head at the top of the transformer
        #  this is taking the 768 channels of the transformer and up scale that to 
        #   50257 to get the logits for the next token

# both of these are 2-dim tensor and there shape is identical 

In [26]:
# comparing there every single element
(sd_hf['lm_head.weight'] == sd_hf['transformer.wte.weight']).all()
# as you can see that all the elemets are equal

tensor(True)

In [27]:
# checking the data pointer 
print(sd_hf['lm_head.weight'].data_ptr())
print(sd_hf['transformer.wte.weight'].data_ptr())

130897059688403
130897059688403


In [28]:
# as you can see they have the same pointer to data as well. 
# so what's happending here is that they have same weight are sharing b/w these two

# look the 3.4 Embedding and softmax section of attention all you need paper
# The original ideas comes from the paper: Using output embedding to Language models

# intiutive idea
# You want these two matrices to behave similar in the following sense
# if two tokens are very similar semantically like one of them is a lowercase and other 
# is all uppercase or the same token in a different langauage or something like that. 

# If you have similarity b/w two token presumbly you would expect that they are near by 
# in the token embedding space but in the exact same way you'd except that if you have two 
# tokens that are similar semantically you'd except them to get same probablities at the 
# output of the transfomer because they are semantically similar. 

# so both positions in the transfomers at the very bottom and at the top have this property 
# that similar tokens should have similar embeddings.

# They also observed (in the paper) if you look at the output embeddings they also behaves 
# like word embeddings 

# so basicalyy wte is used twice 
# 1. at the bottom of the transformer 
# 2. at the top of the transformer
# and In the backward pass we will get gradient contributions from both branches and 
# these gradients will add up on wte tensor
# so we will get contribution from the classifier layer and also at the bottom of the 
# transfomer 

# other than this this also helps in computations. as you can these are lot of 
# parameters

In [29]:
50257 * 768

38597376

In [ ]:
# rought like 40M parameters are shared 

- So that's the change we want to make in out code. is to share wte 
--- 
- after changing the code

In [ ]:
# sing device: cuda
# loaded 338025 tokens
# 1 epoch = 2640 batches
# step 0, loss: 10.969259262084961
# step 1, loss: 9.712841033935547
# step 2, loss: 9.00924015045166
# step 3, loss: 9.145369529724121
# step 4, loss: 8.583311080932617
# step 5, loss: 8.283556938171387
# step 6, loss: 8.973587989807129
# step 7, loss: 8.775681495666504
# step 8, loss: 8.148415565490723
# step 9, loss: 7.83228063583374
# step 10, loss: 8.298928260803223
# step 11, loss: 7.384541034698486
# step 12, loss: 7.6895294189453125
# step 13, loss: 7.419340133666992
# step 14, loss: 7.567596435546875
# step 15, loss: 7.4096784591674805
# step 16, loss: 7.3226213455200195
# step 17, loss: 8.266316413879395
# step 18, loss: 7.1639533042907715
# step 19, loss: 7.797882556915283
# step 20, loss: 7.549393177032471
# step 21, loss: 7.749938011169434
# step 22, loss: 6.446366786956787
# step 23, loss: 6.835708141326904
# step 24, loss: 6.883994102478027
# step 25, loss: 6.704035758972168
# step 26, loss: 6.787974834442139
# step 27, loss: 7.700334072113037
# step 28, loss: 7.19415807723999
# step 29, loss: 7.0182342529296875
# step 30, loss: 6.9842987060546875
# step 31, loss: 7.323225498199463
# step 32, loss: 7.172547340393066
# step 33, loss: 7.044727325439453
# step 34, loss: 7.917436122894287
# step 35, loss: 7.7980523109436035
# step 36, loss: 7.7756428718566895
# step 37, loss: 7.733654499053955
# step 38, loss: 8.064729690551758
# step 39, loss: 7.523628234863281
# step 40, loss: 7.474881172180176
# step 41, loss: 7.044745922088623
# step 42, loss: 7.131816387176514
# step 43, loss: 7.149776458740234
# step 44, loss: 7.066969394683838
# step 45, loss: 7.148806095123291
# step 46, loss: 6.268684387207031
# step 47, loss: 6.4054179191589355
# step 48, loss: 6.962234020233154
# step 49, loss: 6.824957847595215

----
## Fixing model Intialization
----

- the GPT2 and GPT3 paper are not clear about the intinilzation of the weighs. So we will look the GPT2 code.
- Along with the intinalzation from the code. when you look at the GPT2 paper under take 2. "we scale the weights of residual layers at initialization by a factor of 1/ sqrt(N) where N is the number of residual layers. 

In [30]:
# motivation on the second point on what mean in the paper. 
# you start with zero in the residual stream \
# if you look the code where we added the residuals 
    # def forward(self, x): of class Block
    #     x = x + self.attn(self.ln_1(x))
    #     x = x + self.mlp(self.ln_2(x))
# due to this addition the varience of these activations in 
# residual stream grows 

x = torch.zeros(768) # this is the residual stream 
n = 100 # eg: 100 layers 

for i in range(n):
    # randn: gives us the normal distribution with 
    # mean = 0 and std =1 
    x += torch.randn(768)

print(x.std())

tensor(9.9437)


In [ ]:
# and due to this addtion if you all the std() at the end 
# it grows to 10.
# and the scaling factor that they used in the paper is exactly compensates 
# for that growth. 

# Now, if we scale down every one of these contributions by 1/sqrt(N)

In [32]:
x = torch.zeros(768) # this is the residual stream 
n = 100 # eg: 100 layers 
for i in range(n):
    # randn: gives us the normal distribution with 
    # mean = 0 and std =1 
    x += n ** -0.5 * torch.randn(768)
print(x.std())

tensor(1.0184)


In [33]:
# now, if we scale in this then you can see we got 1. 

- So this is the way to control the growth of activations inside the residual stream in the forward pass. 

In [ ]:
# we want to initilizat the weight at the end of each block so the .c_proj(x) layer 
# so we go where have intinilized c_proj i.e 
# to do this we go to CausalSelfAttention --> __init__ 

        # self.c_proj.NANOGPT_SCALE_INIT = 1
#  NANOGPT_SCALE_INIT this will act like as a flag to set the scaling in std
            # if hasattr(module, 'NANOGPT_SCALE_INIT'):
            #     std *= (2 * self.config.n_layer) ** -0.5
# (what we discuss above)

In [ ]:
            # if hasattr(module, 'NANOGPT_SCALE_INIT'):
            #     std *= (2 * self.config.n_layer) ** -0.5